// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9E5x1qS-Uw9qEu3toh3W4zvYL4HLZTDk',
    appId: '1:293714246844:web:9544a8fab60684ac9ee4b9',
    messagingSenderId: '293714246844',
    projectId: 'homebuddy-b084b',
    authDomain: 'homebuddy-b084b.firebaseapp.com',
    storageBucket: 'homebuddy-b084b.firebasestorage.app',
    measurementId: 'G-KWVS8X6CH3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9Wb5xTHyunr6VV-u5EgoaH7Ls33ENQuE',
    appId: '1:293714246844:android:36d7485a28eaa0719ee4b9',
    messagingSenderId: '293714246844',
    projectId: 'homebuddy-b084b',
    storageBucket: 'homebuddy-b084b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAav2ePvIZ2SmBPiuh8NV_HXsbBBU16DVQ',
    appId: '1:293714246844:ios:7bdcfc7a6808aed79ee4b9',
    messagingSenderId: '293714246844',
    projectId: 'homebuddy-b084b',
    storageBucket: 'homebuddy-b084b.firebasestorage.app',
    iosBundleId: 'com.example.homebuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAav2ePvIZ2SmBPiuh8NV_HXsbBBU16DVQ',
    appId: '1:293714246844:ios:7bdcfc7a6808aed79ee4b9',
    messagingSenderId: '293714246844',
    projectId: 'homebuddy-b084b',
    storageBucket: 'homebuddy-b084b.firebasestorage.app',
    iosBundleId: 'com.example.homebuddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9E5x1qS-Uw9qEu3toh3W4zvYL4HLZTDk',
    appId: '1:293714246844:web:07271accbb8ccabd9ee4b9',
    messagingSenderId: '293714246844',
    projectId: 'homebuddy-b084b',
    authDomain: 'homebuddy-b084b.firebaseapp.com',
    storageBucket: 'homebuddy-b084b.firebasestorage.app',
    measurementId: 'G-ZD5LLESWTL',
  );
}
